server:
  port: 8082
spring:
  application:
    name: bionicpro-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/reports-realm
          jwk-set-uri: http://keycloak:8080/auth/realms/reports-realm/protocol/openid-connect/certs
