spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/reports-realm
      client:
        registration:
          keycloak:
            client-id: reports-api
            client-secret: oNwoLQdvJAvRcL89SydqCWCe5ry1jMgq
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/keycloak
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/reports-realm
            user-name-attribute: preferred_username
server:
  port: 8000

logging:
  level:
    org.springframework.security: TRACE